# Generated by Django 4.1.7 on 2023-10-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="balance",
            field=models.FloatField(default=0.0),
        ),
    ]
