# Generated by Django 4.1.7 on 2023-10-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_return',
            field=models.BooleanField(default=False),
        ),
    ]
