# Generated by Django 4.1.7 on 2023-10-16 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_profile_has_return'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='has_return',
        ),
    ]
