# Generated by Django 4.1.7 on 2023-10-03 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0002_profile_balance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="add_cash",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="additional_cash",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="cash",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="opening_cash",
        ),
    ]
