# Generated by Django 4.1.7 on 2023-10-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0003_remove_profile_add_cash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="add_cash",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="profile",
            name="additional_cash",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="profile",
            name="cash",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="profile",
            name="opening_cash",
            field=models.FloatField(default=0.0),
        ),
    ]
