# Generated by Django 4.1.7 on 2023-10-16 12:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agents', '0003_remove_profile_has_return'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ledger',
            new_name='Ledgerr',
        ),
    ]
