# Generated by Django 4.1.7 on 2023-10-09 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_profile_add_cash_profile_additional_cash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='add_cash',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cash',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='has_return',
        ),
    ]
