# Generated by Django 4.1.7 on 2023-10-16 12:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agents', '0004_rename_ledger_ledgerr'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ledgerr',
            new_name='Ledger',
        ),
    ]
