# Generated by Django 4.1.7 on 2023-04-01 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0004_alter_branch_teller_alter_zone_supervisor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branch",
            name="teller",
        ),
        migrations.AddField(
            model_name="branch",
            name="additional_cash",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="branch",
            name="closing_balance",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="branch",
            name="opening_cash",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="branch",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="agents.zone",
            ),
        ),
    ]
