# Generated by Django 4.1.7 on 2023-10-16 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_rename_ledgerr_ledger'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ledger',
        ),
    ]
