# Generated by Django 4.1.7 on 2023-04-03 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("agents", "0005_remove_branch_teller_branch_additional_cash_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branch",
            name="additional_cash",
        ),
        migrations.RemoveField(
            model_name="branch",
            name="closing_balance",
        ),
        migrations.RemoveField(
            model_name="branch",
            name="opening_cash",
        ),
        migrations.RemoveField(
            model_name="branch",
            name="zone",
        ),
        migrations.AddField(
            model_name="branch",
            name="teller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
