# Generated by Django 4.1.7 on 2023-04-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0006_remove_branch_additional_cash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="has_return",
            field=models.BooleanField(default=False),
        ),
    ]
