# Generated by Django 4.1.7 on 2023-03-10 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("owner", models.CharField(max_length=100)),
                ("balance", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ZoneVault",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("opening_cash", models.FloatField()),
                ("additional_cash", models.FloatField()),
                ("euro", models.IntegerField(blank=True, default=0, null=True)),
                ("us_dollar", models.IntegerField(blank=True, default=0, null=True)),
                ("gbp_pound", models.IntegerField(blank=True, default=0, null=True)),
                ("swiss_krona", models.IntegerField(blank=True, default=0, null=True)),
                ("nor_krona", models.IntegerField(blank=True, default=0, null=True)),
                ("swiss_franck", models.IntegerField(blank=True, default=0, null=True)),
                ("cfa", models.IntegerField(blank=True, default=0, null=True)),
                ("denish_krona", models.IntegerField(blank=True, default=0, null=True)),
                ("cad_dollar", models.IntegerField(blank=True, default=0, null=True)),
                ("closing_balance", models.FloatField()),
                ("approved", models.BooleanField(default=False)),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Withdraw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("approved", models.BooleanField(default=False)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vault_manager.account",
                    ),
                ),
                (
                    "withdrawer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MainVault",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("opening_cash", models.FloatField()),
                ("additional_cash", models.FloatField()),
                ("euro", models.IntegerField(blank=True, default=0, null=True)),
                ("us_dollar", models.IntegerField(blank=True, default=0, null=True)),
                ("gbp_pound", models.IntegerField(blank=True, default=0, null=True)),
                ("swiss_krona", models.IntegerField(blank=True, default=0, null=True)),
                ("nor_krona", models.IntegerField(blank=True, default=0, null=True)),
                ("swiss_franck", models.IntegerField(blank=True, default=0, null=True)),
                ("cfa", models.IntegerField(blank=True, default=0, null=True)),
                ("denish_krona", models.IntegerField(blank=True, default=0, null=True)),
                ("cad_dollar", models.IntegerField(blank=True, default=0, null=True)),
                ("closing_balance", models.FloatField()),
                ("approved", models.BooleanField(default=False)),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Deposit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deposit_type", models.CharField(max_length=60)),
                ("amount", models.FloatField()),
                ("approved", models.BooleanField(default=False)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vault_manager.account",
                    ),
                ),
                (
                    "depositor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
