# Generated by Django 4.1.7 on 2023-03-11 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
        ("vault_manager", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deposit",
            old_name="approved",
            new_name="status",
        ),
        migrations.RenameField(
            model_name="mainvault",
            old_name="approved",
            new_name="status",
        ),
        migrations.RenameField(
            model_name="withdraw",
            old_name="approved",
            new_name="status",
        ),
        migrations.RenameField(
            model_name="zonevault",
            old_name="approved",
            new_name="status",
        ),
        migrations.AddField(
            model_name="mainvault",
            name="zone",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="agents.zone",
            ),
        ),
    ]
