# Generated by Django 4.1.7 on 2023-10-04 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault_manager", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="zonevault",
            name="cad_dollar",
        ),
        migrations.RemoveField(
            model_name="zonevault",
            name="cfa",
        ),
        migrations.RemoveField(
            model_name="zonevault",
            name="denish_krona",
        ),
        migrations.RemoveField(
            model_name="zonevault",
            name="euro",
        ),
        migrations.RemoveField(
            model_name="zonevault",
            name="gbp_pound",
        ),
        migrations.RemoveField(
            model_name="zonevault",
            name="nor_krona",
        ),
        migrations.RemoveField(
            model_name="zonevault",
            name="swiss_franck",
        ),
        migrations.RemoveField(
            model_name="zonevault",
            name="swiss_krona",
        ),
        migrations.RemoveField(
            model_name="zonevault",
            name="us_dollar",
        ),
        migrations.AlterField(
            model_name="zonevault",
            name="additional_cash",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="zonevault",
            name="closing_balance",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="zonevault",
            name="opening_cash",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
