# Generated by Django 4.1.7 on 2023-10-09 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault_manager', '0002_remove_zonevault_cad_dollar_remove_zonevault_cfa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainvault',
            name='additional_cash',
        ),
        migrations.RemoveField(
            model_name='mainvault',
            name='cad_dollar',
        ),
        migrations.RemoveField(
            model_name='mainvault',
            name='cfa',
        ),
        migrations.RemoveField(
            model_name='mainvault',
            name='denish_krona',
        ),
        migrations.RemoveField(
            model_name='mainvault',
            name='euro',
        ),
        migrations.RemoveField(
            model_name='mainvault',
            name='gbp_pound',
        ),
        migrations.RemoveField(
            model_name='mainvault',
            name='nor_krona',
        ),
        migrations.RemoveField(
            model_name='mainvault',
            name='opening_cash',
        ),
        migrations.RemoveField(
            model_name='mainvault',
            name='swiss_franck',
        ),
        migrations.RemoveField(
            model_name='mainvault',
            name='swiss_krona',
        ),
        migrations.RemoveField(
            model_name='mainvault',
            name='us_dollar',
        ),
        migrations.RemoveField(
            model_name='zonevault',
            name='additional_cash',
        ),
        migrations.RemoveField(
            model_name='zonevault',
            name='opening_cash',
        ),
    ]
