# Generated by Django 4.1.7 on 2023-03-11 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "vault_manager",
            "0003_alter_mainvault_options_alter_zonevault_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DepositType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="deposit",
            name="deposit_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="vault_manager.deposittype",
            ),
        ),
    ]
