# Generated by Django 4.1.7 on 2023-03-11 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vault_manager", "0004_deposittype_alter_deposit_deposit_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="withdraw",
            options={"verbose_name_plural": "Withdrawals"},
        ),
    ]
