# Generated by Django 4.1.7 on 2023-10-28 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault_manager', '0004_alter_account_date_alter_bank_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencytransaction',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 28, 10, 25, 27, 807250, tzinfo=datetime.timezone.utc)),
        ),
    ]
