# Generated by Django 4.1.7 on 2023-03-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault_manager", "0005_alter_withdraw_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deposit",
            old_name="depositor",
            new_name="agent",
        ),
        migrations.AddField(
            model_name="deposit",
            name="cashier",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="deposit",
            name="supervisor",
            field=models.BooleanField(default=False),
        ),
    ]
