# Generated by Django 4.1.7 on 2023-03-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "vault_manager",
            "0006_rename_depositor_deposit_agent_deposit_cashier_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="deposit",
            name="deposit_type",
            field=models.CharField(
                choices=[
                    ("Opening Cash", "Opening Cash"),
                    ("Additional Cash", "Additional Cash"),
                ],
                max_length=50,
            ),
        ),
    ]
