# Generated by Django 4.1.7 on 2023-03-20 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vault_manager", "0007_alter_deposit_deposit_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DepositType",
        ),
    ]
