# Generated by Django 4.1.7 on 2023-10-28 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vault_manager', '0009_alter_currencytransaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencytransaction',
            name='date_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='currencytransaction',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
