# Generated by Django 4.1.7 on 2023-04-01 10:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("vault_manager", "0011_alter_mainvault_additional_cash_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name="withdraw",
            name="address",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="withdraw",
            name="check_number",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="withdraw",
            name="customer",
            field=models.CharField(default="", max_length=61),
        ),
        migrations.AddField(
            model_name="withdraw",
            name="phone",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="withdraw",
            name="bank",
            field=models.ForeignKey(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vault_manager.bank",
            ),
        ),
    ]
