# Generated by Django 4.1.7 on 2023-04-01 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vault_manager", "0012_bank_withdraw_address_withdraw_check_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="withdraw",
            name="bank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vault_manager.bank",
            ),
        ),
        migrations.AlterField(
            model_name="withdraw",
            name="check_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="withdraw",
            name="customer",
            field=models.CharField(blank=True, max_length=61, null=True),
        ),
        migrations.AlterField(
            model_name="withdraw",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
