# Generated by Django 4.1.7 on 2023-10-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault_manager', '0013_alter_account_date_alter_bank_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankdeposit',
            old_name='status',
            new_name='approved',
        ),
        migrations.RenameField(
            model_name='borrow',
            old_name='status',
            new_name='approved',
        ),
        migrations.RenameField(
            model_name='currencytransaction',
            old_name='status',
            new_name='approved',
        ),
        migrations.RenameField(
            model_name='deposit',
            old_name='status',
            new_name='approved',
        ),
        migrations.RenameField(
            model_name='mainvault',
            old_name='status',
            new_name='approved',
        ),
        migrations.RenameField(
            model_name='withdraw',
            old_name='status',
            new_name='approved',
        ),
        migrations.RenameField(
            model_name='zonevault',
            old_name='status',
            new_name='approved',
        ),
        migrations.AddField(
            model_name='bankdeposit',
            name='disapproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='borrow',
            name='disapproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='currencytransaction',
            name='disapproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deposit',
            name='disapproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mainvault',
            name='disapproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='disapproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zonevault',
            name='disapproved',
            field=models.BooleanField(default=False),
        ),
    ]
