# Generated by Django 4.1.7 on 2023-04-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "vault_manager",
            "0013_alter_withdraw_bank_alter_withdraw_check_number_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="withdraw",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
