# Generated by Django 4.1.7 on 2024-01-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault_manager', '0014_rename_status_bankdeposit_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='refund_type',
            field=models.CharField(choices=[('Opening', 'Opening'), ('Additional', 'Additional')], max_length=50),
        ),
    ]
