# Generated by Django 4.1.7 on 2023-04-01 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vault_manager", "0014_alter_withdraw_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="withdraw",
            name="address",
        ),
        migrations.RemoveField(
            model_name="withdraw",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="withdraw",
            name="phone",
        ),
        migrations.CreateModel(
            name="Borrow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(blank=True, max_length=61, null=True),
                ),
                ("address", models.CharField(blank=True, max_length=100, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("amount", models.FloatField()),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("status", models.BooleanField(default=False)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vault_manager.account",
                    ),
                ),
                (
                    "borrower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Withdrawals",
            },
        ),
    ]
