# Generated by Django 4.1.7 on 2023-04-01 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "vault_manager",
            "0015_remove_withdraw_address_remove_withdraw_customer_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrow",
            name="address",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="borrow",
            name="customer_name",
            field=models.CharField(default="", max_length=61),
        ),
        migrations.AlterField(
            model_name="borrow",
            name="phone",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="withdraw",
            name="bank",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="vault_manager.bank",
            ),
        ),
        migrations.AlterField(
            model_name="withdraw",
            name="check_number",
            field=models.CharField(default="", max_length=100),
        ),
    ]
