# Generated by Django 4.1.7 on 2023-04-01 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "vault_manager",
            "0016_alter_borrow_address_alter_borrow_customer_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="withdraw",
            name="bank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="vault_manager.bank"
            ),
        ),
    ]
