# Generated by Django 4.1.7 on 2023-04-01 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vault_manager", "0019_alter_withdraw_bank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="withdraw",
            name="bank",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="vault_manager.bank",
            ),
        ),
        migrations.AlterField(
            model_name="withdraw",
            name="check_number",
            field=models.CharField(max_length=100),
        ),
    ]
