# Generated by Django 4.1.7 on 2023-04-04 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vault_manager", "0027_currency"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrencyTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=50)),
                ("phone_number", models.CharField(max_length=50)),
                ("id_number", models.CharField(max_length=50)),
                ("sell", models.BooleanField(default=False)),
                ("buy", models.BooleanField(default=False)),
                (
                    "type",
                    models.CharField(
                        choices=[("buy", "buy"), ("sell", "sell")], max_length=20
                    ),
                ),
                ("currency_amount", models.FloatField()),
                ("rate", models.FloatField()),
                ("total_amount", models.FloatField()),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vault_manager.currency",
                    ),
                ),
            ],
        ),
    ]
