# Generated by Django 4.1.7 on 2023-04-04 17:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("vault_manager", "0028_currencytransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="currencytransaction",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
