# Generated by Django 4.1.7 on 2023-04-06 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vault_manager", "0031_currencytransaction_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currencytransaction",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="vault_manager.account"
            ),
        ),
    ]
