# Generated by Django 4.1.7 on 2023-04-06 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vault_manager", "0032_alter_currencytransaction_account"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="currencytransaction",
            name="buy",
        ),
        migrations.RemoveField(
            model_name="currencytransaction",
            name="sell",
        ),
    ]
