# Generated by Django 4.1.7 on 2023-04-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault_manager", "0033_remove_currencytransaction_buy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="withdraw",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
