# Generated by Django 4.1.7 on 2023-04-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault_manager", "0034_withdraw_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="zonevault",
            name="location",
        ),
        migrations.AddField(
            model_name="zonevault",
            name="cashier_name",
            field=models.CharField(default="", max_length=50),
        ),
    ]
