# Generated by Django 4.1.7 on 2023-04-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault_manager", "0035_remove_zonevault_location_zonevault_cashier_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zonevault",
            name="cashier_name",
            field=models.CharField(max_length=50),
        ),
    ]
