# Generated by Django 4.1.7 on 2023-09-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault_manager", "0036_alter_zonevault_cashier_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="withdraw",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="cheque_images"),
        ),
    ]
